Update demo.yml

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -37,7 +37,7 @@ jobs:
   #        python -m pip install pytest
   #    - name: Test
   #      run: pytest
-  validate_pr_title:
+  validate_pr_title1:
     env: 
       REGEX: ^\(TA\|ESS\|EIT\|DEVOPS\|AS\)-[0-9]{4,6}:.[A-Za-z]+.*$
       TITLE: ${{ github.event.pull_request.title }}
@@ -46,6 +46,58 @@ jobs:
       - run: |
           [[ $TITLE =~ $REGEX ]] && (echo "INVALID=false" >> $GITHUB_ENV) || (echo "INVALID=true" >> $GITHUB_ENV)
           echo "PR is valid: $INVALID"
+      - run: echo "$INVALID"
+      - name: Leave comment to change title on PR
+        uses: actions/github-script@v3
+        if: ${{ github.env.INVALID }}
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body:`Please update PR Title to match the following pattern. 
+                (TA|ESS|EIT|AS|DEVOPS)-{id}: summary of change
+                Example: *TA-12345: Update pytest to latest version*`
+            });
+            core.setFailed("Invalid PR Title")
+  validate_pr_title2:
+    env: 
+      REGEX: ^\(TA\|ESS\|EIT\|DEVOPS\|AS\)-[0-9]{4,6}:.[A-Za-z]+.*$
+      TITLE: ${{ github.event.pull_request.title }}
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          if [[ $TITLE =~ $REGEX ]] then
+            echo "INVALID=false" >> $GITHUB_ENV)
+          else
+            (echo "INVALID=true" >> $GITHUB_ENV)
+          fi
+      - run: echo "$INVALID"
+      - name: Leave comment to change title on PR
+        if: ${{ github.env.INVALID }}
+        uses: actions/github-script@v3
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body:`Please update PR Title to match the following pattern. 
+                (TA|ESS|EIT|AS|DEVOPS)-{id}: summary of change
+                Example: *TA-12345: Update pytest to latest version*`
+            });
+            core.setFailed("Invalid PR Title")
+  validate_pr_title3:
+    env: 
+      REGEX: ^\(TA\|ESS\|EIT\|DEVOPS\|AS\)-[0-9]{4,6}:.[A-Za-z]\+.*$
+      TITLE: ${{ github.event.pull_request.title }}
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          [[ $TITLE =~ $REGEX ]] && (echo "INVALID=false" >> $GITHUB_ENV) || (echo "INVALID=true" >> $GITHUB_ENV)
+          echo "PR is valid: $INVALID"
+      - run: echo "$INVALID"
       - name: Leave comment to change title on PR
         if: ${{ github.env.INVALID }}
         uses: actions/github-script@v3
